<a href="https://colab.research.google.com/github/2SEHI/K-Digital_Lecture/blob/main/00_test/%5B%EA%B3%BC%EC%A0%9C%5DPython%EB%B6%84%EC%84%9D%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC%ED%99%9C%EC%9A%A9_%EC%9D%B4%EC%84%B8%ED%9D%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2021. 7. 22제출

In [ ]:
import pandas as pd 
import numpy as np
import seaborn as sns

> ## Q1. `arange()`, `reshape()` 이용 1차원 2차원 3차원 배열을 아래와 같이 생성하세요.

    [0 1 2 3 4 5 6 7 8 9]
    [[0 1 2 3 4]
    [5 6 7 8 9]]
    [[[0 1 2 3 4]
    [5 6 7 8 9]]]

### 나의 답안

In [ ]:
# 답
print(np.arange(10))
print(np.arange(10).reshape(2,5))
print(np.arange(10).reshape(1,2,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


### 선생님 답안

In [ ]:
# -1이나 1 둘다 가능
print(np.arange(10).reshape(1,2,5))
print(np.arange(10).reshape(-1,2,5))

[[[0 1 2 3 4]
  [5 6 7 8 9]]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


---

> ## Q2. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력하세요.

### 나의 답안

In [ ]:
# 답
for i in range(1,101):
    if (i % 5 == 0) & (i % 2 == 0):
        print(i)

10
20
30
40
50
60
70
80
90
100


### 선생님 답안

In [ ]:
ar = np.arange(1, 101)
li = []
for i in range(len(ar)):
    if (ar[i] % 5 == 0) & (ar[i] % 2 == 0):
        print(ar[i])

10
20
30
40
50
60
70
80
90
100


---

> ## Q3. 아래 3차원 배열을 생성하여 출력한 후 1차원으로 변환하여 출력하세요.

    [[[ 0 1 2 3 4]
    [ 5 6 7 8 9]]
    [[10 11 12 13 14]
    [15 16 17 18 19]]
    [[20 21 22 23 24]
    [25 26 27 28 29]]]


### 나의 답안

In [ ]:
# 답
arr3d = np.arange(30).reshape(3,2,5)
print(arr3d)
print(arr3d.flatten())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


### 선생님 답안

In [ ]:
# 답
arr3d = np.arange(30).reshape(-1,2,5)
print(arr3d)

# 일차원 배열로 변환 - flatten
print(arr3d.reshape(-1))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


---
> ## Q4. array2d에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.

    arr2d = np.arange(1,10).reshape(3,3)
    [3, 6]
    [[1, 2],
    [4, 5]]
    [[1, 2, 3]
    [4, 5, 6]


In [ ]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 나의 답안

In [ ]:
# 답
print(arr2d[:2,2])
print(arr2d[:2,:2])
print(arr2d[:2,:])

[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


### 선생님 답안

In [ ]:
# 답
print(arr2d[0][2], arr2d[1][2])
print(arr2d[:2,:2])
print(arr2d[:2,:])

3 6
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


---

> ## Q5. 아래 두행렬을 np.arange, reshape를 이용해서 생성 각각 a1, b1으로 저장하고 행렬 내적을 계산한 결과를 출력하세요

    [[1 2 3]
    [4 5 6]
    [7 8 9]]
    [[10 11]
    [12 13]
    [14 15]]


### 나의 답안

In [ ]:
# 답
a1 = np.arange(1,10).reshape(3,3)
b1 = np.arange(10,16).reshape(3,2)
# 내적 행렬
a1.dot(b1)

array([[ 76,  82],
       [184, 199],
       [292, 316]])

### 선생님 답안

In [ ]:
# 답
a1 = np.arange(1,10).reshape(3,3)
b1 = np.arange(10,16).reshape(3,2)
print(a1)
print(b1)

# 내적은 dot
a1.dot(b1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11]
 [12 13]
 [14 15]]


array([[ 76,  82],
       [184, 199],
       [292, 316]])

---
> ## Q6. [[1,2,3],[11,12,13]] 리스트와 array([[ 1, 2, 3],[11, 12, 13]]) 배열을 대입하고 컬럼명을 'col1','col2','col3'으로 하는 데이터프레임을 작성하세요


### 나의 답안

In [ ]:
# 답
# 리스트
list1 = [[1,2,3],[11,12,13]]
array2 = np.array(list1)
columns =['col1','col2','col3']
newArr = pd.concat([pd.DataFrame(list1),pd.DataFrame(array2)])
newArr.rename(columns={0:'col1',1:'col2',2:'col3'},inplace=True)
newArr

col1  col2  col3
0     1     2     3
1    11    12    13
0     1     2     3
1    11    12    13

### 선생님 답안

In [ ]:
# 답
# 리스트
list_a = [[1,2,3],[11,12,13]]
ar = np.array(list_a)
columns =['col1','col2','col3']
df1 = pd.concat(list_a, columns=columns)
df2 = pd.concat(ar, columns=columns)

df2.rename(columns={0:'col1',1:'col2',2:'col3'},inplace=True)
df2

TypeError: ignored

---
> ## Q7. 10 ~ 20 사이의 정수 난수로 10행 5열 2차원 행렬을 생성하고 컬럼명이 A B C D E인 데이터프레임을 작성하세요


### 나의 답안

In [ ]:
# 답
rArr = np.random.randint(10, 20, size=(10, 5))
pd.DataFrame(rArr, columns=['A','B','C','D','E'])

A   B   C   D   E
0  17  11  14  10  14
1  16  16  17  13  16
2  15  10  16  10  10
3  13  16  12  11  17
4  13  15  17  17  11
5  18  10  12  17  14
6  14  13  11  14  15
7  14  15  11  17  18
8  18  10  10  12  19
9  18  19  19  16  14

### 선생님 답안

In [ ]:
# 답
ar = np.random.randint(10, 20, size=(10, 5))
print(ar)
columns = ['A', 'B', 'C','D','E']
df = pd.DataFrame(data=ar, columns=columns)

[[19 14 19 16 10]
 [19 18 19 17 14]
 [15 15 16 13 12]
 [15 12 12 13 15]
 [11 10 10 12 16]
 [11 13 16 16 14]
 [16 17 17 13 10]
 [10 17 18 17 16]
 [16 17 18 12 19]
 [14 19 15 13 19]]


---
> ## Q8. df = sns.load_dataset('titanic')로 불러와서 다음 작업을 수행한 후 출력하세요.
- 전체 칼럼중 'survived'외에 모든 칼럼을 포함한 df_x를 산출한 후 dataset/df_x.pkl로 저장한다.
- df_x.pkl을 데이터프레임 df_x 이름으로 불러온 후 앞 5개 행을 출력한다.

### 나의 답안

In [ ]:
df = sns.load_dataset('titanic')
df_x = df.drop(labels='survived', axis=1)

df_x.to_pickle("/dataset/df_x.pkl")

df_x2 = pd.read_pickle("/dataset/df_x.pkl")
df_x2.head(5)

pclass     sex   age  sibsp  ...  deck  embark_town alive  alone
0       3    male  22.0      1  ...   NaN  Southampton    no  False
1       1  female  38.0      1  ...     C    Cherbourg   yes  False
2       3  female  26.0      0  ...   NaN  Southampton   yes   True
3       1  female  35.0      1  ...     C  Southampton   yes  False
4       3    male  35.0      0  ...   NaN  Southampton    no   True

[5 rows x 14 columns]

### 선생님 답안
- pickle.으로 해도 되고 to_pickle로 해도 됩니다

In [ ]:
df = sns.load_dataset('titanic')
columns_list = df.columns.to_list()
print(columns_list)
columns_list.remove('survived')
df1 = pd.DataFrame(data=df, columns=columns_list)
df1
import pickle
with open('df_x_plt', 'wb') as f:
    pickle.dump(df1, f)

with open('df_x_plt', 'rb') as f:
    df_x = pickle.load(f)
    print(df_x.head(5))



['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']
   pclass     sex   age  sibsp  ...  deck  embark_town alive  alone
0       3    male  22.0      1  ...   NaN  Southampton    no  False
1       1  female  38.0      1  ...     C    Cherbourg   yes  False
2       3  female  26.0      0  ...   NaN  Southampton   yes   True
3       1  female  35.0      1  ...     C  Southampton   yes  False
4       3    male  35.0      0  ...   NaN  Southampton    no   True

[5 rows x 14 columns]


In [ ]:
df = sns.load_dataset('titanic')
# 컬럼 삭제
df_x = df.drop(labels='survived', axis=1)

# dataframe파일로 저장
df_x.to_pickle("/dataset/df_x.pkl")
# dataframe파일 불러오기
df_x2 = pd.read_pickle("/dataset/df_x.pkl")
df_x2.head(5)

---
> ## Q9. df = sns.load_dataset('titanic')로 불러와서 deck 열에서 NaN 갯수를 계산하세요.

### 나의 답안

In [ ]:
df = sns.load_dataset('titanic')
df['deck'].isnull().sum()

688

### 선생님 답안

In [ ]:
df = sns.load_dataset('titanic')
df['deck'].isnull().sum()

688

---
> ## Q10. Q9의 df에서 각 칼럼별 null 개수와 df 전체의 null 개수를 구하세요.

### 나의 답안

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

### 선생님 답안

In [ ]:
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


> ## 아래 tdf 데이터프레임에서 Q11 ~ Q12 작업을 수행하세요.

In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class']]
tdf.head()

survived     sex   age  class
0         0    male  22.0  Third
1         1  female  38.0  First
2         1  female  26.0  Third
3         1  female  35.0  First
4         0    male  35.0  Third

---
> ## Q11. age를 7개 카테고리로 구분하는 새로운 칼럼 'cat_age'를 생성하여 출력하세요.
단, 카테고리 구분을 수행하는 사용자 함수를 만들고 그 함수를 age 칼럼에 매핑하여 결
과를 tdf1에 저장하고 출력하세요.

    [카테고리]
    age <= 5: cat = 'Baby'
    age <= 12: cat = 'Child'
    age <= 18: cat = 'Teenager'
    age <= 25: cat = 'Student'
    age <= 60: cat = 'Adult'
    age > 60 : cat = 'Elderly'

### 나의 답안

In [ ]:
import math
def ageCategorical(age):
    cat = 'Elderly'
    if math.isnan(age):
        cat = np.nan
    else :         
        age = int(age)
        if age <= 5: 
            cat = 'Baby'
        elif age > 5 and age <= 12: 
            cat = 'Child'
        elif age > 12 and age <= 18:
            cat = 'Teenager'
        elif age > 18 and age <= 25: 
            cat = 'Student'
        elif age > 25 and age <= 60: 
            cat = 'Adult'
        elif age > 60:
            cat = 'Elderly'
    return cat

tdf1= tdf.copy()
tdf1['age_cat'] = tdf1['age'].apply(ageCategorical)
tdf1['age_cat'] = pd.Categorical(tdf1['age_cat'], categories=bins, ordered=False)
tdf1

survived     sex   age   class  age_cat
0           0    male  22.0   Third  Student
1           1  female  38.0   First    Adult
2           1  female  26.0   Third    Adult
3           1  female  35.0   First    Adult
4           0    male  35.0   Third    Adult
..        ...     ...   ...     ...      ...
886         0    male  27.0  Second    Adult
887         1  female  19.0   First  Student
888         0  female   NaN   Third      NaN
889         1    male  26.0   First    Adult
890         0    male  32.0   Third    Adult

[891 rows x 5 columns]

### 선생님 답안

In [ ]:
import math
def ageCategorical(age):
    cat = 'Elderly'
    if math.isnan(age):
        cat = np.nan
    else :         
        age = int(age)
        if age <= 5: 
            cat = 'Baby'
        elif age > 5 and age <= 12: 
            cat = 'Child'
        elif age > 12 and age <= 18:
            cat = 'Teenager'
        elif age > 18 and age <= 25: 
            cat = 'Student'
        elif age > 25 and age <= 60: 
            cat = 'Adult'
        elif age > 60:
            cat = 'Elderly'
    return cat

tdf1= tdf.copy()
tdf1['age_cat'] = tdf1['age'].apply(ageCategorical)
print(tdf1.head())

tdf1['age_cat'] = pd.Categorical(tdf1['age_cat'], categories=bins, ordered=False)
tdf1

---
> ## Q12. tdf1의 sex, class 칼럼을 '_'으로 연결한 'sc'칼럼을 추가한 후 아래와 같이 출력하세요.


### 나의 답안

In [ ]:
# 출력 결과
tdf1['sc'] = tdf1['sex'] + '_' +tdf1['class'].astype(str)
tdf1

survived     sex   age   class  age_cat            sc
0           0    male  22.0   Third  Student    male_Third
1           1  female  38.0   First    Adult  female_First
2           1  female  26.0   Third    Adult  female_Third
3           1  female  35.0   First    Adult  female_First
4           0    male  35.0   Third    Adult    male_Third
..        ...     ...   ...     ...      ...           ...
886         0    male  27.0  Second    Adult   male_Second
887         1  female  19.0   First  Student  female_First
888         0  female   NaN   Third      NaN  female_Third
889         1    male  26.0   First    Adult    male_First
890         0    male  32.0   Third    Adult    male_Third

[891 rows x 6 columns]

### 선생님 답안

In [ ]:
# t2. tdf1의 sex, class컬럼을 '_'으로 조인하여 새로운 컬럼을 만듦
tdf1['sc'] = tdf1[['sex', 'class']].agg('_'.join, axis=1)
print(tdf1tdf1.head())

## Q13.Numpy의 join함수 역할
- 일반적으로 동일한 구조를 가지는 2개 이상의 배열을 합치는 것입니다.
- 배열을 합치고자 할 때는 concatenate와 같은 함수를 이용

---
> ## Q14. 아래 df에서 drop_duplicates() 메소드를 사용하여 c2, c3열을 기준으로 중복 행을 제거한 후 df3에 저장하고 출력하세요.
- drop_duplicates() : 매개변수로 넘겨준 컬럼에 대해 중복된 행을 제거하는 함수

In [ ]:
# 중복 데이터를 갖는 데이터프레임 만들기
import pandas as pd
df = pd.DataFrame({'c1':['a', 'a', 'b', 'a', 'b'],
 'c2':[1, 1, 1, 2, 2],
 'c3':[1, 1, 2, 2, 2]})
print(df)

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2


### 나의 답안

In [ ]:
df3 = df.drop_duplicates(subset=['c2', 'c3'])
print(df3)

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2


---
> ## Q15. 'mpg'를 'kpl' 로 환산하여 새로운 열을 생성하고 처음 3개 행을 소수점 아래 둘째자리에서 반올림하여 출력하세요.

In [ ]:
# read_csv() 함수로 df 생성
import pandas as pd
auto_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/auto-mpg.csv')
# 열 이름을 지정
auto_df.columns = ['mpg','cylinders','displacement','horsepower','weight',
 'acceleration','model year','origin','name'] 
print(auto_df.head(3))

    mpg  cylinders  displacement  ... model year  origin                name
0  15.0          8         350.0  ...         70       1   buick skylark 320
1  18.0          8         318.0  ...         70       1  plymouth satellite
2  16.0          8         304.0  ...         70       1       amc rebel sst

[3 rows x 9 columns]


### 나의 답안

In [ ]:
auto_df['kpl'] = round((auto_df['mpg'] * 1.609344)/3.785411784, 2)
auto_df['kpl'].head(3)

0    6.38
1    7.65
2    6.80
Name: kpl, dtype: float64

### 선생님 답안

In [ ]:
auto_df['kpl'] = df['mpg'] * 0.425
auto_df['kpl'] = auto_df['kpl'].round(2)
print(auto_df.head())

---
> ## Q16. './dataset/stock-data.csv'를 데이터프레임으로 불러와서 datetime64 자료형으로 변환한 후에 년, 월, 일로 분리하고 year를 인덱스로 셋팅하여 출력하세요.

### 나의 답안

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/stock-data.csv')
df['Date'] = pd.to_datetime(df['Date'])
year_index = df['Date'].map(lambda x : x.year)
df = df.set_index(year_index)
df

Date  Close  Start   High    Low  Volume
Date                                               
2018 2018-07-02  10100  10850  10900  10000  137977
2018 2018-06-29  10700  10550  10900   9990  170253
2018 2018-06-28  10400  10900  10950  10150  155769
2018 2018-06-27  10900  10800  11050  10500  133548
2018 2018-06-26  10800  10900  11000  10700   63039
2018 2018-06-25  11150  11400  11450  11000   55519
2018 2018-06-22  11300  11250  11450  10750  134805
2018 2018-06-21  11200  11350  11750  11200  133002
2018 2018-06-20  11550  11200  11600  10900  308596
2018 2018-06-19  11300  11850  11950  11300  180656
2018 2018-06-18  12000  13400  13400  12000  309787
2018 2018-06-15  13400  13600  13600  12900  201376
2018 2018-06-14  13450  13200  13700  13150  347451
2018 2018-06-12  13200  12200  13300  12050  558148
2018 2018-06-11  11950  12000  12250  11950   62293
2018 2018-06-08  11950  11950  12200  11800   59258
2018 2018-06-07  11950  12200  12300  11900   49088
2018 2018-06-05  12150  11800  12250  11800   42485
2018 2018-06-04  11900  11900  12200  11700   25171
2018 2018-06-01  11900  11800  12100  11750   32062

### 선생님 답안

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/stock-data.csv')
print(df.head())
df['new_date'] = pd.to_datetime(df['Date'])
print(df.head())
print(df.info())
df['year'] = df['new_date'].dt.year
df['month'] = df['new_date'].dt.month
df['day'] = df['new_date'].dt.day
print(df)

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039
         Date  Close  Start   High    Low  Volume   new_date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      20 non-null     object        
 1   Close     20 non-null     int64         
 2   Start     20 non-null     int64         
 3

---
> ## Q17. titanic 데이터셋에서 5개 열을 선택해서 class열을 기준으로 그룹화를 수행한 후 아래와 같이 출력하였다. 다음 사항을 출력하세요.
- 5개 열 : ['age','sex', 'class', 'fare', 'survived']
- 그룹별 평균 출력
- 그룹별 최대값 출력


### 나의 답안

In [ ]:
df = sns.load_dataset('titanic')
columns =  ['age','sex', 'class', 'fare', 'survived']
df1 = pd.DataFrame(df, columns=columns)

print(df1.groupby('class').mean())
print(df1.groupby('class').max())

              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363
         age   sex      fare  survived
class                                 
First   80.0  male  512.3292         1
Second  70.0  male   73.5000         1
Third   74.0  male   69.5500         1


### 선생님 답안

In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')
df_five = df.loc[:, ['age','sex', 'class', 'fare', 'survived']]
df_five.head()
print()

grouped = df_five.groupby('class')
print(grouped.mean())
print(grouped.max())


              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363
         age   sex      fare  survived
class                                 
First   80.0  male  512.3292         1
Second  70.0  male   73.5000         1
Third   74.0  male   69.5500         1


---
> ## Q18. titanic 데이터셋에서 'Third'그룹만을 선택해서 group3 이름으로 저장하고 통계요약표를 출력하세요.

### 나의 답안

In [ ]:
group3 = df.groupby('class').get_group('Third')
group3.describe()

survived  pclass         age       sibsp       parch        fare
count  491.000000   491.0  355.000000  491.000000  491.000000  491.000000
mean     0.242363     3.0   25.140620    0.615071    0.393075   13.675550
std      0.428949     0.0   12.495398    1.374883    0.888861   11.778142
min      0.000000     3.0    0.420000    0.000000    0.000000    0.000000
25%      0.000000     3.0   18.000000    0.000000    0.000000    7.750000
50%      0.000000     3.0   24.000000    0.000000    0.000000    8.050000
75%      0.000000     3.0   32.000000    1.000000    0.000000   15.500000
max      1.000000     3.0   74.000000    8.000000    6.000000   69.550000

### 선생님 답안

In [ ]:
group_class = df.groupby('class')
group3 = group_class.get_group('Third')
group3.describe()

survived  pclass         age       sibsp       parch        fare
count  491.000000   491.0  355.000000  491.000000  491.000000  491.000000
mean     0.242363     3.0   25.140620    0.615071    0.393075   13.675550
std      0.428949     0.0   12.495398    1.374883    0.888861   11.778142
min      0.000000     3.0    0.420000    0.000000    0.000000    0.000000
25%      0.000000     3.0   18.000000    0.000000    0.000000    7.750000
50%      0.000000     3.0   24.000000    0.000000    0.000000    8.050000
75%      0.000000     3.0   32.000000    1.000000    0.000000   15.500000
max      1.000000     3.0   74.000000    8.000000    6.000000   69.550000

---
> ## Q19. titanic 데이터셋에서 class 열, sex열 기준으로 그룹화한 후 그룹별 평균과 표준편차를 구하세요.

### 나의 답안

In [ ]:
print(df.groupby(['class','sex']).mean())
print(df.groupby(['class','sex']).std())

               survived  pclass        age  ...        fare  adult_male     alone
class  sex                                  ...                                  
First  female  0.968085     1.0  34.611765  ...  106.125798    0.000000  0.361702
       male    0.368852     1.0  41.281386  ...   67.226127    0.975410  0.614754
Second female  0.921053     2.0  28.722973  ...   21.970121    0.000000  0.421053
       male    0.157407     2.0  30.740707  ...   19.741782    0.916667  0.666667
Third  female  0.500000     3.0  21.750000  ...   16.118810    0.000000  0.416667
       male    0.135447     3.0  26.507589  ...   12.661633    0.919308  0.760807

[6 rows x 8 columns]
               survived  pclass        age  ...       fare  adult_male     alone
class  sex                                  ...                                 
First  female  0.176716     0.0  13.612052  ...  74.259988    0.000000  0.483070
       male    0.484484     0.0  15.139570  ...  77.548021    0.155511  0.48866

### 선생님 답안

In [ ]:
grouped = df.groupby(['class','sex'])
print(grouped.mean())
print(grouped.std())

               survived  pclass        age  ...        fare  adult_male     alone
class  sex                                  ...                                  
First  female  0.968085     1.0  34.611765  ...  106.125798    0.000000  0.361702
       male    0.368852     1.0  41.281386  ...   67.226127    0.975410  0.614754
Second female  0.921053     2.0  28.722973  ...   21.970121    0.000000  0.421053
       male    0.157407     2.0  30.740707  ...   19.741782    0.916667  0.666667
Third  female  0.500000     3.0  21.750000  ...   16.118810    0.000000  0.416667
       male    0.135447     3.0  26.507589  ...   12.661633    0.919308  0.760807

[6 rows x 8 columns]
               survived  pclass        age  ...       fare  adult_male     alone
class  sex                                  ...                                 
First  female  0.176716     0.0  13.612052  ...  74.259988    0.000000  0.483070
       male    0.484484     0.0  15.139570  ...  77.548021    0.155511  0.48866

---
> ## Q20. titanic 데이터셋에서 다음 전처리를 수행하세요.
1. df에서 중복 칼럼 6개를 삭제한 후 df1 이름으로 저장 후 5개 행을 출력하세요.
2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 데체 처리를 수행하세요.
4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 데체 처리를 수행하세요.
5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

### 나의 답안

In [ ]:
# 1. df에서 중복 칼럼 6개를 삭제한 후 df1 이름으로 저장 후 5개 행을 출력하세요.
columns = ['survived','pclass','sex','age','sibsp','parch','fare','embarked','deck']
df1 = pd.DataFrame(df,columns=columns)
df1.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [ ]:
# 2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
df2 = df1.dropna(thresh=(len(df1) / 2), axis=1)
df2

survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [ ]:
# 3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 대체 처리를 수행하세요.
df2['age'] = df2['age'].fillna(value=df2['age'].mean())
print(df2)
df2.info()

     survived  pclass     sex        age  sibsp  parch     fare embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 column

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
# 4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 대체 처리를 수행하세요.
df2['embarked'] = df2['embarked'].fillna(method='ffill')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
# 5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요
from sklearn.preprocessing import LabelEncoder

labelEcd = LabelEncoder()
df2['sex'] = labelEcd.fit_transform(df2['sex'].values)
df2['embarked'] = labelEcd.fit_transform(df2['embarked'].values)
df2.info()
print(df2.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    int64  
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB
   survived  pclass  sex   age  sibsp  parch     fare  embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


### 선생님 답안

---
> ## Q20. titanic 데이터셋에서 다음 전처리를 수행하세요.
1. df에서 중복 칼럼 6개를 삭제한 후 df1 이름으로 저장 후 5개 행을 출력하세요.
2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 데체 처리를 수행하세요.
4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 데체 처리를 수행하세요.
5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')
df1 = df[['survived', 'pclass','sex','age','sibsp','parch','fare','embarked', 'deck']]
print(df1.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN


In [ ]:
# 2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
print(df1.info())
df2 = df1.drop(['deck'], axis=1)
print(df2.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   survived  891 non-null    int64   
 1   pclass    891 non-null    int64   
 2   sex       891 non-null    object  
 3   age       714 non-null    float64 
 4   sibsp     891 non-null    int64   
 5   parch     891 non-null    int64   
 6   fare      891 non-null    float64 
 7   embarked  889 non-null    object  
 8   deck      203 non-null    category
dtypes: category(1), float64(2), int64(4), object(2)
memory usage: 57.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64 

In [ ]:
# 3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 데체 처리를 수행하세요.
df2.age.fillna(df2.age.mean(), inplace=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
# 4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 데체 처리를 수행하세요.
df2.embarked.fillna(method='ffill', inplace=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
# 5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

from sklearn import preprocessing

features = ['sex', 'embarked']
for feature in features:
    # 라벨 인코더
    le = preprocessing.LabelEncoder()
    # 인코딩된 데이터로 데이터를 변경
    df2[feature] = le.fit_transform(df2[feature])
df2.info()
print(df2.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    int64  
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB
   survived  pclass  sex   age  sibsp  parch     fare  embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2
